### ISSUE TITLE
Ajouter un texte explication footer

### ISSUE THREAD

**Issue by florianpanchout** [betagouv/ecolab-calculateurco2inverse#11]
Texte à fournir par l'ABC ?

**Comment by martinregner** [comment]
En attente texte Fanny

**Comment by florianpanchout** [comment]
@martinregner A qui s'adresse ce simulateur ? Parce que ce texte me semble très indigeste pour l'utilisateur moyen. Je peux le retoucher un peu ?

**Comment by martinregner** [comment]
Oui vas-y ! N'hésite pas à le remanier @florianpanchout ! :)

**Comment by florianpanchout** [comment]
Je n'ai pas touché à son texte mais j'ai ajouté un peu de contenu avant

**Comment by martinregner** [comment]
OK super !
Peut-être juste changer le "Ces correspondances ..." en "Les correspondances proposées dans ce convertisseur ..." pour être sûr d'être bien compris.

Par contre je pense qu'il y a trop de CTA. En particulier, l'article de blog est un peu dur en premier bouton. Vu qu'il est aussi accessible via NGC, je te propose de simplifier en réorganisant :

![image](https://user-images.githubusercontent.com/46482115/106268185-06ac4100-622b-11eb-876e-063c4217769b.png)
![image](https://user-images.githubusercontent.com/46482115/106268206-0f9d1280-622b-11eb-907e-d7e989ed4771.png)
![image](https://user-images.githubusercontent.com/46482115/106268288-2ba0b400-622b-11eb-8e29-e13ea02c9df5.png)

**Comment by florianpanchout** [comment]
C'est fait :)

**Comment by martinregner** [comment]
Top ! :)
