### ISSUE TITLE
Ajouter le chauffage gaz

### ISSUE THREAD

**Issue by martinregner** [betagouv/ecolab-calculateurco2inverse#13]
- Cf. NGC, 1 an de chauffage = 3.4tCO2 : https://nosgestesclimat.fr/documentation/logement/gaz
- Peut-être donc parler en "mois de chauffage d'un logement" ? --> 1tCO2 = 3,5 mois

Proposition emoji : 🏘️

**Comment by florianpanchout** [comment]
J'ai mis "Jour[s] de chauffage au gaz". Ca te va ?

**Comment by martinregner** [comment]
Top ! (cf. #14 j'ai modifié le FE)
