### ISSUE TITLE
Décrire et afficher les hypothèses

### ISSUE THREAD

**Issue by martinregner** [betagouv/ecolab-calculateurco2inverse#18]
Pour les équivalents où un « recalcul » a été nécessaire, et qu’il ne s’agit pas directement de l’application d’un FE de la Base Carbone, il serait utile d’expliciter le calcul (ou a minima les hypothèses pour que les utilisateurs s’y retrouvent). 
C'est le cas par ex. pour « jour de chauffage » , « feuille de papier », ...

Serait-il possible d'avoir un texte visible au clic / au survol sur la case en question sur le calculateur ?

**Comment by florianpanchout** [comment]
J'ai ajouté les hypothèse pour le poids du livre et le chauffage au gaz. Tu en vois d'autres à préciser ?

**Comment by martinregner** [comment]
Quelques petites modifs dans #21 

Je pense qu'il serait intéressant d'ajouter le nom du facteur d'émission pour ceux qui le cherchent dans la Base Carbone.
Ca me va de les rajouter, mais on aura un petit "?" à chaque case (peut-être plus cohérent d'avoir d'un point de vue utilisateur), et un contenu du genre :
> "Source : Base Carbone, facteur d'émissions "repas  ..."
> _le cas échéant les hypothèses_ 

Ca sera aussi plus cohérent avec les hypothèses affichées dans le [calculateur transport](https://ecolab.ademe.fr/apps/transport)

Qu'en penses-tu @florianpanchout ?

**Comment by florianpanchout** [comment]
C'est fait. Je n'ai pas trouvé tes sources pour kg d'ordures ménagères et Litre[s] d'eau de source par contre

**Comment by martinregner** [comment]
Oh top !! Merci @florianpanchout ! 👍 👍 
Je regarde pour compléter.

**Comment by martinregner** [comment]
ajouté avec #22
