### ISSUE TITLE
Unité

### ISSUE THREAD

**Issue by laem** [betagouv/ecolab-calculateurco2inverse#2]
https://github.com/betagouv/ecolab-calculateurco2inverse/blob/6cbb96695474a1bc6bcdf5b1aa05d89887a49fe0/src/views/comparator/co2Input/NumberInput.js#L87

Je crois qu'on écrit plutôt kgCO2e ou kg de CO2e.

Autre solution : kg de GES, en définissant GES = gaz à effet de serre. C'est moins courant, mais c'est peut-être à nous de faire évoluer le discours pour qu'il soit compréhensible.

**Comment by laem** [comment]
On pourrait même parler de kilos climat, à creuser. On peut évidemment rester sur kgCO2e dans une 1ère itération.

**Comment by florianpanchout** [comment]
Je trouve kg de GES et kilos climat beaucoup moins explicites. CO2 est rentré dans le langage courant ce qui fait que kgCO2e est directement compréhensible.

**Comment by laem** [comment]
Okay, je vais tester ça dans mon entourage / sur les réseaux :)

**Comment by florianpanchout** [comment]
Changé pour kgC02e

**Comment by laem** [comment]
On gardera la réflexion de l'unité en tête pendant longtemps encore, je ferme donc
