### ISSUE TITLE
Bug affichage sur safari

### ISSUE THREAD

**Issue by martinregner** [betagouv/ecolab-calculateurco2inverse#27]
- Sur la zone de saisie du montant en kgCO2
- Sur la bulle info : les chiffres des cases objets se mettent par dessus la bulle
- Sur iPad : ne s'affiche pas du tout ; le site appairait 1 seconde puis l'écran devient intégralement blanc

![Capture d’écran 2021-02-06 à 10 17 13](https://user-images.githubusercontent.com/46482115/107114353-7c389280-6865-11eb-8eff-e1887876e4fc.png)

**Comment by florianpanchout** [comment]
C'est corrigé !
