### ISSUE TITLE
Définition CO2e

### ISSUE THREAD

**Issue by Clem-mrtn** [betagouv/ecolab-calculateurco2inverse#3]
Pour moi il faudrait rajouter la définition du C02e directement sur le simulateur (Même si aujourd'hui on redirige l'utilisateur sur la définition du C02e du Gitbook) : 
ex:  CO2e*
_* définition_  

=> plus pédagogue (c'est le but du simulateur) / on perd moins l'utilisateur  ?

**Comment by florianpanchout** [comment]
Ajouté en popin. J'ai repris le texte de la doc. Il y a peut être plus digeste ?

**Comment by martinregner** [comment]
@Clem-mrtn ou @florianpanchout je suis preneur d'une version plus digeste, avec plaisir !

Déjà ça commence par "_GES anthropiques_"... ça fait un peu peur 😋 --> _Gaz à Effet de Serre (GES) liés à l'activité humaine_ ?

**Comment by florianpanchout** [comment]
J'ai repris le texte de futur.eco :)

**Comment by martinregner** [comment]
Top ! Bon, sauf que l'exemple est faux 🙈
(1 L de lait = 1,49 kg CO2e donc 6 L ça fait 8,94... et pas 30. Peut-être à corriger sur futur.eco @laem ? 😄 )

J'ai repris le même ex. 1kg CH4 + 1kg CO2 mais sans parler du produit, cf. #20
