### ISSUE TITLE
C02e : mettre 2 en indice

### ISSUE THREAD

**Issue by florianpanchout** [betagouv/ecolab-calculateurco2inverse#8]

**Comment by martinregner** [comment]
Oups j'avais pas vu quand tu as créé l'issue @florianpanchout sorry. C'est le 2 qui peut être en indice, le e reste au niveau du haut 🙂 
https://fr.wikipedia.org/wiki/%C3%89quivalent_CO2

**Comment by florianpanchout** [comment]
That make more sense...

C'est corrigé

**Comment by martinregner** [comment]
Top ! Possible aussi sur le titre ?

**Comment by florianpanchout** [comment]
J'ai essayé, c'est peu esthétique. Dis moi ce que tu en penses

**Comment by martinregner** [comment]
Je suis pas sûr d'être très objectif ;) ... mais je trouve que ça donne une bonne cohérence sur toute la page comme ça 👍
